<?xml version="1.0" encoding="UTF-8"?>
<data version="1.0">
    <struct type="Settings">
        <key>fileFormatVersion</key>
        <int>0</int>
        <key>variation</key>
        <string>main</string>
        <key>verbose</key>
        <false/>
        <key>autoSDSettings</key>
        <array/>
        <key>allowRotation</key>
        <false/>
        <key>quiet</key>
        <false/>
        <key>premultiplyAlpha</key>
        <false/>
        <key>shapeDebug</key>
        <false/>
        <key>dpi</key>
        <uint>72</uint>
        <key>dataFormat</key>
        <string>sparrow</string>
        <key>textureFileName</key>
        <filename>tiles.png</filename>
        <key>flipPVR</key>
        <false/>
        <key>ditherType</key>
        <enum type="SettingsBase::DitherType">NearestNeighbour</enum>
        <key>backgroundColor</key>
        <uint>0</uint>
        <key>libGdx</key>
        <struct type="LibGDX">
            <key>filtering</key>
            <struct type="LibGDXFiltering">
                <key>x</key>
                <enum type="LibGDXFiltering::Filtering">Linear</enum>
                <key>y</key>
                <enum type="LibGDXFiltering::Filtering">Linear</enum>
            </struct>
        </struct>
        <key>shapePadding</key>
        <uint>0</uint>
        <key>jpgQuality</key>
        <uint>80</uint>
        <key>pngOptimizationLevel</key>
        <uint>0</uint>
        <key>textureSubPath</key>
        <string></string>
        <key>textureFormat</key>
        <enum type="SettingsBase::TextureFormat">png</enum>
        <key>borderPadding</key>
        <uint>0</uint>
        <key>maxTextureSize</key>
        <QSize>
            <key>width</key>
            <int>1024</int>
            <key>height</key>
            <int>1024</int>
        </QSize>
        <key>fixedTextureSize</key>
        <QSize>
            <key>width</key>
            <int>-1</int>
            <key>height</key>
            <int>-1</int>
        </QSize>
        <key>reduceBorderArtifacts</key>
        <false/>
        <key>algorithmSettings</key>
        <struct type="AlgorithmSettings">
            <key>algorithm</key>
            <enum type="AlgorithmSettings::AlgorithmId">MaxRects</enum>
            <key>freeSizeMode</key>
            <enum type="AlgorithmSettings::AlgorithmFreeSizeMode">Best</enum>
            <key>sizeConstraints</key>
            <enum type="AlgorithmSettings::SizeConstraints">NPOT</enum>
            <key>forceSquared</key>
            <true/>
            <key>forceWordAligned</key>
            <false/>
            <key>maxRects</key>
            <struct type="AlgorithmMaxRectsSettings">
                <key>heuristic</key>
                <enum type="AlgorithmMaxRectsSettings::Heuristic">Best</enum>
            </struct>
            <key>basic</key>
            <struct type="AlgorithmBasicSettings">
                <key>sortBy</key>
                <enum type="AlgorithmBasicSettings::SortBy">Best</enum>
                <key>order</key>
                <enum type="AlgorithmBasicSettings::Order">Ascending</enum>
            </struct>
        </struct>
        <key>andEngine</key>
        <struct type="AndEngine">
            <key>minFilter</key>
            <enum type="AndEngine::MinFilter">Linear</enum>
            <key>packageName</key>
            <string>Texture</string>
            <key>javaFileName</key>
            <filename>tiles.java</filename>
            <key>wrap</key>
            <struct type="AndEngineWrap">
                <key>s</key>
                <enum type="AndEngineWrap::Wrap">Clamp</enum>
                <key>t</key>
                <enum type="AndEngineWrap::Wrap">Clamp</enum>
            </struct>
            <key>magFilter</key>
            <enum type="AndEngine::MagFilter">MagLinear</enum>
        </struct>
        <key>dataFileName</key>
        <filename>tiles.xml</filename>
        <key>mainExtension</key>
        <string></string>
        <key>forceIdenticalLayout</key>
        <false/>
        <key>outputFormat</key>
        <enum type="SettingsBase::OutputFormat">RGBA8888</enum>
        <key>autoAliasEnabled</key>
        <true/>
        <key>trimSpriteNames</key>
        <false/>
        <key>globalSpriteSettings</key>
        <struct type="SpriteSettings">
            <key>scale</key>
            <double>0.45714</double>
            <key>scaleMode</key>
            <enum type="ScaleMode">Smooth</enum>
            <key>innerPadding</key>
            <uint>0</uint>
            <key>extrude</key>
            <uint>0</uint>
            <key>trimThreshold</key>
            <uint>1</uint>
            <key>trimMode</key>
            <enum type="SpriteSettings::TrimMode">None</enum>
            <key>heuristicMask</key>
            <false/>
        </struct>
        <key>fileList</key>
        <array>
            <filename>../Tiles/stoneCenter.png</filename>
            <filename>../Tiles/stoneCenter_rounded.png</filename>
            <filename>../Tiles/stoneCliffLeft.png</filename>
            <filename>../Tiles/stoneCliffLeftAlt.png</filename>
            <filename>../Tiles/stoneCliffRight.png</filename>
            <filename>../Tiles/stoneCliffRightAlt.png</filename>
            <filename>../Tiles/stoneHalf.png</filename>
            <filename>../Tiles/stoneHalfLeft.png</filename>
            <filename>../Tiles/stoneHalfMid.png</filename>
            <filename>../Tiles/stoneHalfRight.png</filename>
            <filename>../Tiles/stoneHillLeft2.png</filename>
            <filename>../Tiles/stoneHillRight2.png</filename>
            <filename>../Tiles/stoneLeft.png</filename>
            <filename>../Tiles/stoneMid.png</filename>
            <filename>../Tiles/stoneRight.png</filename>
            <filename>../Tiles/stoneWall.png</filename>
            <filename>../Tiles/tochLit.png</filename>
            <filename>../Tiles/tochLit2.png</filename>
            <filename>../Tiles/torch.png</filename>
            <filename>../Tiles/window.png</filename>
            <filename>../Tiles/box.png</filename>
            <filename>../Tiles/boxAlt.png</filename>
            <filename>../Tiles/boxCoin.png</filename>
            <filename>../Tiles/boxCoin_disabled.png</filename>
            <filename>../Tiles/boxCoinAlt.png</filename>
            <filename>../Tiles/boxCoinAlt_disabled.png</filename>
            <filename>../Tiles/boxEmpty.png</filename>
            <filename>../Tiles/boxExplosive.png</filename>
            <filename>../Tiles/boxExplosive_disabled.png</filename>
            <filename>../Tiles/boxExplosiveAlt.png</filename>
            <filename>../Tiles/boxItem.png</filename>
            <filename>../Tiles/boxItem_disabled.png</filename>
            <filename>../Tiles/boxItemAlt.png</filename>
            <filename>../Tiles/boxItemAlt_disabled.png</filename>
            <filename>../Tiles/boxWarning.png</filename>
            <filename>../Tiles/brickWall.png</filename>
            <filename>../Tiles/bridge.png</filename>
            <filename>../Tiles/bridgeLogs.png</filename>
            <filename>../Tiles/castle.png</filename>
            <filename>../Tiles/castleCenter.png</filename>
            <filename>../Tiles/castleCenter_rounded.png</filename>
            <filename>../Tiles/castleCliffLeft.png</filename>
            <filename>../Tiles/castleCliffLeftAlt.png</filename>
            <filename>../Tiles/castleCliffRight.png</filename>
            <filename>../Tiles/castleCliffRightAlt.png</filename>
            <filename>../Tiles/castleHalf.png</filename>
            <filename>../Tiles/castleHalfLeft.png</filename>
            <filename>../Tiles/castleHalfMid.png</filename>
            <filename>../Tiles/castleHalfRight.png</filename>
            <filename>../Tiles/castleHillLeft.png</filename>
            <filename>../Tiles/castleHillLeft2.png</filename>
            <filename>../Tiles/castleHillRight.png</filename>
            <filename>../Tiles/castleHillRight2.png</filename>
            <filename>../Tiles/castleLeft.png</filename>
            <filename>../Tiles/castleMid.png</filename>
            <filename>../Tiles/castleRight.png</filename>
            <filename>../Tiles/dirt.png</filename>
            <filename>../Tiles/dirtCenter.png</filename>
            <filename>../Tiles/dirtCenter_rounded.png</filename>
            <filename>../Tiles/dirtCliffLeft.png</filename>
            <filename>../Tiles/dirtCliffLeftAlt.png</filename>
            <filename>../Tiles/dirtCliffRight.png</filename>
            <filename>../Tiles/dirtCliffRightAlt.png</filename>
            <filename>../Tiles/dirtHalf.png</filename>
            <filename>../Tiles/dirtHalfLeft.png</filename>
            <filename>../Tiles/dirtHalfMid.png</filename>
            <filename>../Tiles/dirtHalfRight.png</filename>
            <filename>../Tiles/dirtHillLeft.png</filename>
            <filename>../Tiles/dirtHillLeft2.png</filename>
            <filename>../Tiles/dirtHillRight.png</filename>
            <filename>../Tiles/dirtHillRight2.png</filename>
            <filename>../Tiles/dirtLeft.png</filename>
            <filename>../Tiles/dirtMid.png</filename>
            <filename>../Tiles/dirtRight.png</filename>
            <filename>../Tiles/door_closedMid.png</filename>
            <filename>../Tiles/door_closedTop.png</filename>
            <filename>../Tiles/door_openMid.png</filename>
            <filename>../Tiles/door_openTop.png</filename>
            <filename>../Tiles/fence.png</filename>
            <filename>../Tiles/fenceBroken.png</filename>
            <filename>../Tiles/grass.png</filename>
            <filename>../Tiles/grassCenter.png</filename>
            <filename>../Tiles/grassCenter_rounded.png</filename>
            <filename>../Tiles/grassCliffLeft.png</filename>
            <filename>../Tiles/grassCliffLeftAlt.png</filename>
            <filename>../Tiles/grassCliffRight.png</filename>
            <filename>../Tiles/grassCliffRightAlt.png</filename>
            <filename>../Tiles/grassHalf.png</filename>
            <filename>../Tiles/grassHalfLeft.png</filename>
            <filename>../Tiles/grassHalfMid.png</filename>
            <filename>../Tiles/grassHalfRight.png</filename>
            <filename>../Tiles/grassHillLeft.png</filename>
            <filename>../Tiles/grassHillLeft2.png</filename>
            <filename>../Tiles/grassHillRight.png</filename>
            <filename>../Tiles/grassHillRight2.png</filename>
            <filename>../Tiles/grassLeft.png</filename>
            <filename>../Tiles/grassMid.png</filename>
            <filename>../Tiles/grassRight.png</filename>
            <filename>../Tiles/ladder_mid.png</filename>
            <filename>../Tiles/ladder_top.png</filename>
            <filename>../Tiles/liquidLava.png</filename>
            <filename>../Tiles/liquidLavaTop.png</filename>
            <filename>../Tiles/liquidLavaTop_mid.png</filename>
            <filename>../Tiles/liquidWater.png</filename>
            <filename>../Tiles/liquidWaterTop.png</filename>
            <filename>../Tiles/liquidWaterTop_mid.png</filename>
            <filename>../Tiles/lock_blue.png</filename>
            <filename>../Tiles/lock_green.png</filename>
            <filename>../Tiles/lock_red.png</filename>
            <filename>../Tiles/lock_yellow.png</filename>
            <filename>../Tiles/rockHillLeft.png</filename>
            <filename>../Tiles/rockHillRight.png</filename>
            <filename>../Tiles/ropeAttached.png</filename>
            <filename>../Tiles/ropeHorizontal.png</filename>
            <filename>../Tiles/ropeVertical.png</filename>
            <filename>../Tiles/sand.png</filename>
            <filename>../Tiles/sandCenter.png</filename>
            <filename>../Tiles/sandCenter_rounded.png</filename>
            <filename>../Tiles/sandCliffLeft.png</filename>
            <filename>../Tiles/sandCliffLeftAlt.png</filename>
            <filename>../Tiles/sandCliffRight.png</filename>
            <filename>../Tiles/sandCliffRightAlt.png</filename>
            <filename>../Tiles/sandHalf.png</filename>
            <filename>../Tiles/sandHalfLeft.png</filename>
            <filename>../Tiles/sandHalfMid.png</filename>
            <filename>../Tiles/sandHalfRight.png</filename>
            <filename>../Tiles/sandHillLeft.png</filename>
            <filename>../Tiles/sandHillLeft2.png</filename>
            <filename>../Tiles/sandHillRight.png</filename>
            <filename>../Tiles/sandHillRight2.png</filename>
            <filename>../Tiles/sandLeft.png</filename>
            <filename>../Tiles/sandMid.png</filename>
            <filename>../Tiles/sandRight.png</filename>
            <filename>../Tiles/sign.png</filename>
            <filename>../Tiles/signExit.png</filename>
            <filename>../Tiles/signLeft.png</filename>
            <filename>../Tiles/signRight.png</filename>
            <filename>../Tiles/snow.png</filename>
            <filename>../Tiles/snowCenter.png</filename>
            <filename>../Tiles/snowCenter_rounded.png</filename>
            <filename>../Tiles/snowCliffLeft.png</filename>
            <filename>../Tiles/snowCliffLeftAlt.png</filename>
            <filename>../Tiles/snowCliffRight.png</filename>
            <filename>../Tiles/snowCliffRightAlt.png</filename>
            <filename>../Tiles/snowHalf.png</filename>
            <filename>../Tiles/snowHalfLeft.png</filename>
            <filename>../Tiles/snowHalfMid.png</filename>
            <filename>../Tiles/snowHalfRight.png</filename>
            <filename>../Tiles/snowHillLeft.png</filename>
            <filename>../Tiles/snowHillLeft2.png</filename>
            <filename>../Tiles/snowHillRight.png</filename>
            <filename>../Tiles/snowHillRight2.png</filename>
            <filename>../Tiles/snowLeft.png</filename>
            <filename>../Tiles/snowMid.png</filename>
            <filename>../Tiles/snowRight.png</filename>
            <filename>../Tiles/stone.png</filename>
        </array>
        <key>ignoreFileList</key>
        <array/>
        <key>replaceList</key>
        <array/>
        <key>commonDivisorX</key>
        <uint>1</uint>
        <key>commonDivisorY</key>
        <uint>1</uint>
    </struct>
</data>
